### ISSUE TITLE
Discount by volume of orders

### ISSUE THREAD

**Issue by aviezab** [hfahmi/edulux#20]

**Comment by aviezab** [comment]
Example:
1 pcs purchase has 0% discount (100% price)
5 pcs purchase has 5% discount (95% price)
The amount of pieces and discount input manually by each vendor.

**Comment by dozymoe** [comment]
> for product dicount configuration, please refer below links,
> https://www.youtube.com/watch?v=xnX0TkmN14k
> https://www.youtube.com/watch?v=LqTzpIkZxeI
> https://www.youtube.com/watch?v=nRjkMRFJ5RE

-- Parth

**Comment by dozymoe** [comment]
Pricelist has been implemented in our development site, see https://github.com/hfahmi/edulux/wiki/Development-Site

But I think we run into a bug from odoo_marketplace itself, so we're going to check that with them, this issue is a close.

Seller's product configuration:

![pricelist_config](https://user-images.githubusercontent.com/1083741/35480517-5e087f08-0442-11e8-8c0c-5b98b23a115f.jpg)

Pricelist not working:

![pricelist_notworking](https://user-images.githubusercontent.com/1083741/35480520-6868a9be-0442-11e8-9fd2-d686b2dfb579.jpg)

Pricelist is working for offline sell:

![pricelist_working](https://user-images.githubusercontent.com/1083741/35480522-68ff2646-0442-11e8-92e6-179418d267a5.jpg)

What online sale quotation looks like:

![pricelist_websale_quotation](https://user-images.githubusercontent.com/1083741/35480521-68af1a02-0442-11e8-98ee-d07e9359e678.jpg)
